# This is a XGS demo HOT template just defining two nets with two middleboxes
heat_template_version: 2013-05-23

description: >
  HOT template that just defines two user vm, a trans_mb and a routed_mb.
  Contains just base components to verify base demo.

parameters:
  user_image_1:
    type: string
    description: ID or name of the image to use for the user instance
    default: user_vm1
  user_image_2:
    type: string
    description: ID or name of the image to use for the user instance
    default: user_vm2
  xgs_image:
    type: string
    description: ID or name of the image to use for the XGS instance
    default: trans_mb
  routed_image:
    type: string
    description: ID or name of the image to use for the routed_mb instance
    default: routed_mb
  user_flavor:
    type: string
    description: Flavor for the user instance to be created
    default: ex.tiny
    constraints:
      - allowed_values: [ex.tiny, ex.xgs]
        description: Value must be one of 'ex.tiny' or 'ex.xgs'
  xgs_flavor:
    type: string
    description: Flavor for the xgs instance to be created
    default: ex.xgs
    constraints:
      - allowed_values: [ex.tiny, ex.xgs]
        description: Value must be one of 'ex.tiny' or 'ex.xgs'
  availability_zone:
    type: string
    description: The Availability Zone to launch the instance.
    default: az1

resources:
#Networks
  net_int1:
    type: OS::Neutron::Net
    properties:
      name: net_int1
  net_int2:
    type: OS::Neutron::Net
    properties:
      name: net_int2
  net_xgs_manage1:
    type: OS::Neutron::Net
    properties:
      name: net_xgs_manage1
  net_xgs_manage2:
    type: OS::Neutron::Net
    properties:
      name: net_xgs_manage2
  net_xgs_data1:
    type: OS::Neutron::Net
    properties:
      name: net_xgs_data1
  net_xgs_data2:
    type: OS::Neutron::Net
    properties:
      name: net_xgs_data2
#Subnets
  subnet_int1:
    type: OS::Neutron::Subnet
    properties:
      name: subnet_int1
      cidr: 192.168.1.0/24
      gateway_ip: 192.168.1.1
      network_id: { get_resource: net_int1 }
      enable_dhcp: True
  subnet_int2:
    type: OS::Neutron::Subnet
    properties:
      name: subnet_int2
      cidr: 192.168.2.0/24
      gateway_ip: 192.168.2.1
      network_id: { get_resource: net_int2 }
  subnet_xgs_manage1:
    type: OS::Neutron::Subnet
    properties:
      name: subnet_xgs_manage1
      cidr: 10.0.1.0/24
      gateway_ip: 10.0.1.1
      network_id: { get_resource: net_xgs_manage1 }
  subnet_xgs_manage2:
    type: OS::Neutron::Subnet
    properties:
      name: subnet_xgs_manage2
      cidr: 10.0.2.0/24
      gateway_ip: 10.0.2.1
      network_id: { get_resource: net_xgs_manage2 }
  subnet_xgs_data1:
    type: OS::Neutron::Subnet
    properties:
      name: subnet_xgs_data1
      cidr: 10.0.3.0/24
      gateway_ip: 10.0.3.1
      network_id: { get_resource: net_xgs_data1 }
  subnet_xgs_data2:
    type: OS::Neutron::Subnet
    properties:
      name: subnet_xgs_data2
      cidr: 10.0.4.0/24
      gateway_ip: 10.0.4.1
      network_id: { get_resource: net_xgs_data2 }
#Routers
  router:
    type: OS::Neutron::Router
    properties:
      name: router
  router_inf1:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet_int1 }
  router_inf2:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet_int2 }
#Servers
  user_vm1:
    type: OS::Nova::Server
    properties:
      name: user_vm1
      image: { get_param: user_image_1 }
      flavor: { get_param: user_flavor }
      networks: [{network:{get_resource: net_int1}}]
      availability_zone: { get_param: availability_zone }
      security_groups: [{ get_resource: the_sg }]
  user_vm2:
    type: OS::Nova::Server
    depends_on: user_vm1
    properties:
      name: user_vm2
      image: { get_param: user_image_2 }
      flavor: { get_param: user_flavor }
      networks: [{network: {get_resource: net_int2}}]
      availability_zone: { get_param: availability_zone }
      security_groups: [{ get_resource: the_sg }]
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            sysctl -w net.ipv4.ip_forward=1
          params:
            param1: test
  xgs_mb:
    type: OS::Nova::Server
    depends_on: [user_vm1, user_vm2]
    properties:
      name: xgs_mb
      image: { get_param: xgs_image }
      flavor: { get_param: xgs_flavor }
      networks: [{network: {get_resource: net_xgs_manage1}},{network: {get_resource: net_xgs_manage2}},{network: {get_resource: net_xgs_data1}},{network: {get_resource: net_xgs_data2}}]
      availability_zone: { get_param: availability_zone }
      security_groups: [{ get_resource: the_sg }]
  routed_mb:
    type: OS::Nova::Server
    depends_on: [user_vm1, user_vm2, xgs_mb]
    properties:
      name: routed_mb
      image: { get_param: routed_image }
      flavor: { get_param: user_flavor }
      networks: [{network: {get_resource: net_int1}},{network: {get_resource: net_int2}}]
      availability_zone: { get_param: availability_zone }
      security_groups: [{ get_resource: the_sg }]
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            sysctl -w net.ipv4.ip_forward=1
          params:
            param1: test
#Others
  the_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: the_sg
      description: Allow Ping, SSH and Web
      rules: 
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: tcp
        port_range_min: 80
        port_range_max: 80
      - protocol: tcp
        port_range_min: 443
        port_range_max: 443
  
outputs:
  user_vm1_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [user_vm1, addresses] }
  user_vm2_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [user_vm2, addresses] }
  routed_mb_ip:
    description: The IP address of the routed middlebox
    value: { get_attr: [routed_mb, addresses] }
  trans_mb_ip:
    description: The IP address of the transparent middlebox
    value: { get_attr: [trans_mb, addresses] }
